# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QstzFVxWhTBVatOEqmDi+DaM2ch6gbRUmAPb9XqWJ2qS7ufNPyjpSKn2a7+BmjGjlC28U+byiPWaEBukD13PMYH6xf3VCsAP2ZGPkWqSO0PNwhmQV9CFfRO9/jY201qOaBTD7ZZgNYW92G/LYiF2VqCXxGDhjsxpEKf+K7GfcEWWrPTfanBF2n8WLco2v0dQf1WGDvivmvJOJ2hy36n9mChTNuhFlhtc7m4hz0FnGAD/6xOPgr/y3nysPOPU9BzScbZeqlrWYt278Eqopa7CCr4FDQs86YUid3lJUf5uMzUQhOBM9Li2cDx+8zGfbu07Dv5LUb8sqfxpOhFVTFUezSWDztAaevd8rZ7EZttvfoCCmS0zUAMG1cw4ES108QIzZpVHFXQFtDqFYcO34zZXyYwwQZFWK312vMVJGfZpSbVV0OIlBSNs3HzgtQPvfm/Lib8N5kMp/m8dnEAAD5KEjPlkqAEE+2mSe30aJiMHRgRwZSNjwjzvXjtj/A7+F/WmAybFVATwjkIud4si20IW0Doj4uUpq5PEh8wIumuthAHTQqr9Jbd20N4znGBWB6OFi9vo8n0ob7iu9Cncv+TPwwI/UjxhR+4pDo90fORncRVUhW1ecK/EOq+Wtp2/KC7tNl+HrlAaz0/quBnafGp3rfxXQZCAKtlHzogHIJpNYrM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
